---
- name: Add user.name to ~/.gitconfig
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ user_git_name }}"

- name: Add user.email to ~/.gitconfig
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ user_git_email }}"

- name: Add code.editor to ~/.gitconfig
  community.general.git_config:
    name: core.editor
    scope: global
    value: "{{ user_setup_git_editor }}"

- name: Add init.defaultBranch to ~/.gitconfig
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Add core.sshCommand to ~/.gitconfig
  community.general.git_config:
    name: core.sshCommand
    scope: global
    value: ssh.exe
