---
- name: Add Block to .bashrc
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    prepend_newline: true
    append_newline: true
    backup: true
    block: "{{ lookup('file', role_path + '/files/append-bashrc.sh') }}"
