---
- name: Fetch latest compose tag
  when: (compose_version is not defined) or (compose_version == 'latest')
  run_once: true
  block:
    - name: Determine latest GitHub release (local)
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: _github_release
      until: _github_release.status == 200
      retries: 5

    - name: Set compose_version
      ansible.builtin.set_fact:
        compose_version: "{{ _github_release.json.tag_name }}"

- name: Set facts cli-plugins dir
  ansible.builtin.set_fact:
    compose_bin_dir: ~/.docker/cli-plugins

- name: Set facts compose bin
  ansible.builtin.set_fact:
    compose_bin: "{{ compose_bin_dir }}/docker-compose"

- name: Check already exists {{ compose_bin }}
  ansible.builtin.stat:
    path: "{{ compose_bin }}"
  register: check_compose

- name: Get installed compose version
  ansible.builtin.command:
    cmd: "{{ compose_bin }} version --format json"
  register: compose_exists
  changed_when: false
  when: check_compose.stat.exists

- name: Set facts compose version
  ansible.builtin.set_fact:
    compose_exists_version: "{{ (compose_exists.stdout | from_json).version }}"
  when: check_compose.stat.exists

- name: Install compose {{ compose_version }}
  when: not check_compose.stat.exists or compose_exists_version != compose_version
  block:
    - name: Ensure a {{ compose_bin_dir }}
      ansible.builtin.file:
        path: "{{ compose_bin_dir }}"
        mode: "0755"
        state: directory

    - name: Remove old version {{ compose_exists_version | default('') }}
      ansible.builtin.file:
        path: "{{ compose_bin }}"
        state: absent
      when: check_compose.stat.exists

    - name: Download compose and verify SHA256 checksum {{ compose_version }}
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-linux-x86_64
        dest: "{{ compose_bin }}"
        mode: "0754"
        checksum: sha256:https://github.com/docker/compose/releases/download/{{ compose_version }}/checksums.txt
