---
- name: Check installed pyenv
  ansible.builtin.stat:
    path: ~/.pyenv
  register: check_pyenv

- name: Instell pyenv
  when: not check_pyenv.stat.exists
  block:
    - name: Ensure a temporary directory for download exists
      ansible.builtin.tempfile:
        state: directory
      register: temp_dir

    - name: Get pyenv installer
      ansible.builtin.get_url:
        url: https://pyenv.run
        dest: "{{ temp_dir.path }}/pyenv.run.sh"
        mode: "0700"
      register: pyenv_installer

    - name: Run pyenv installer
      ansible.builtin.command:
        cmd: "{{ pyenv_installer.dest }}"
        creates: ~/.pyenv

    - name: Remove the temporary directory
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent
      when: temp_dir.path is defined
