---
- name: Set max parallel downloads for DNF
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    create: false
    section: main
    option: max_parallel_downloads
    value: 5

- name: Enable fastestmirror for DNF
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    create: false
    section: main
    option: fastestmirror
    value: false

- name: Enable Fedora Copr for wslu
  community.general.copr:
    name: wslutilities/wslu

- name: Enable Fedora Copr for jbang
  community.general.copr:
    name: "@jbangdev/jbang"

- name: Add Adoptium Repository
  ansible.builtin.yum_repository:
    name: Adoptium
    description: Adoptioum repo
    baseurl: https://packages.adoptium.net/artifactory/rpm/{{ ansible_facts['distribution'].lower() }}/$releasever/$basearch
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://packages.adoptium.net/artifactory/api/gpg/key/public

- name: Update packages
  ansible.builtin.dnf5:
    name: "*"
    update_cache: true
    state: latest

- name: Install packages
  ansible.builtin.dnf5:
    name: "{{ initial_setup_packages['main'] }}"
    update_cache: true
    state: latest
